lines = open('index.html', 'r', encoding='utf-8').readlines()
bad_start = -1
for i, line in enumerate(lines):
    if 'const ctxRel = elemChartRel.getContext' in line and i > 2300:
        bad_start = i
        break
if bad_start != -1:
    lines = lines[:bad_start]
    lines.append('                    \n')
    lines.append('                    const timeRange = timelineMaxTime - timelineMinTime;\n')
    lines.append('                    const targetTime = timelineMinTime + (timeRange * (val / 100));\n')
    lines.append('                    window.timelineCurrentDate = new Date(targetTime);\n')
    lines.append('                    updateTimelineUI();\n')
    lines.append('                    \n')
    lines.append('                    if (typeof allFocos !== "undefined") {\n')
    lines.append('                        const relevantFocos = allFocos.filter(f => f.tipoLocal === "propriedade" || f.tipoLocal === "buffer");\n')
    lines.append('                        processarFocos(relevantFocos);\n')
    lines.append('                    }\n')
    lines.append('                }, 400); // Increased interval to 400ms (slower playback)\n')
    lines.append('            }\n')
    lines.append('        }\n\n')
    lines.append('        window.addEventListener("resize", () => {\n')
    lines.append('            if (window.innerWidth > 768) {\n')
    lines.append('                document.getElementById("map-container").style.display = "";\n')
    lines.append('                document.getElementById("sidebar").style.display = "";\n')
    lines.append('                if(window.map) map.invalidateSize();\n')
    lines.append('            } else {\n')
    lines.append('                if(!document.body.classList.contains("mobile-show-sidebar") && !document.body.classList.contains("mobile-show-map")) {\n')
    lines.append('                    // Estado inicial no mobile\n')
    lines.append('                    switchTab("tab-mapa", document.querySelector(".sidebar-tab.d-mobile-only"));\n')
    lines.append('                }\n')
    lines.append('            }\n')
    lines.append('        });\n\n')
    lines.append('        document.addEventListener("DOMContentLoaded", () => {\n')
    lines.append('            if (window.innerWidth <= 768) {\n')
    lines.append('                setTimeout(() => {\n')
    lines.append('                    switchTab("tab-mapa", document.querySelector(".sidebar-tab.d-mobile-only"));\n')
    lines.append('                }, 100);\n')
    lines.append('            }\n')
    lines.append('            \n')
    lines.append('            // Auto-refresh a cada 5 minutos (300.000 ms)\n')
    lines.append('            setInterval(() => {\n')
    lines.append('                console.log("Auto-refresh: buscando novos focos...");\n')
    lines.append('                if (typeof atualizarFocosBackendProxy === "function") {\n')
    lines.append('                    atualizarFocosBackendProxy();\n')
    lines.append('                }\n')
    lines.append('            }, 300000);\n')
    lines.append('        });\n\n')
    lines.append('    </script>\n\n')
    lines.append('</body>\n\n')
    lines.append('</html>\n')
    open('index.html', 'w', encoding='utf-8').writelines(lines)
    print('Fixed')
else:
    print('Not found')
